In [1]:
import pandas as pd
import numpy as np

import re

## Game Data from NHL Database

We will start with getting the game data the Kaggle NHL Database. The only real reason to do this is to get game id's that we can then use to merge the Natural Stat Trick data with the gambling data. We could also just assign our own game id, which, may be easier.

In [2]:
path = "/home/mark/Dodd/software/Python/data/nhl/nhl-game-data/"

teams = pd.read_csv(path + "team_info.csv")
games_all = pd.read_csv(path + "game.csv")

In [3]:
#display(teams.head())
def get_games(season):
    # convert season into a season number in the same format as the datafile
    season = season * 10000 + (season + 1)
    
    # filter for regular season games of that season
    games = games_all[(games_all['season'] == season) & (games_all['type'] == 'R')].copy()

    # create a small lambda to merge, drop, and rename
    merge_games = lambda df, team: (df.merge(right = teams[['team_id','teamName']], left_on = team + '_id',
                                                right_on = 'team_id')
                                    .drop(columns = ['team_id'])
                                    .rename(columns = {'teamName':team}))
    
    games = merge_games(games, 'away_team')
    games = merge_games(games, 'home_team')
    
    #convert datatypes
    games['date_time'] = pd.to_datetime(games['date_time'], format = '%Y-%m-%d')
    games['outcome'] = games['outcome'].astype('category')
    
    #filter for useful columns
    cols = ['game_id', 'season', 'date_time', 'away_team', 'home_team',
            'away_goals', 'home_goals', 'outcome', 'home_team_id', 'away_team_id']
    games_reduced = games[cols].sort_values(by='game_id')
    
    return games_reduced

In [4]:
g2016 = get_games(2016)
g2017 = get_games(2017)
g2018 = get_games(2018)

## Natural Stat Trick Data

Now, it is time to deal with the Natural Stat Trick Data

Create a number of procedures to make the cleaning more compartmentatlized and repeatable.

Skip to the next cell to actually get going.

In [5]:
def natstat_to_numeric(df_in):
    # '-' were causing some columns to be treated as strings so let's replace and convert
    df = df_in.drop(columns = ["Unnamed: 2", "Attendance"]).replace('-', np.nan)
    df.loc[:,'TOI':] = df.loc[:,'TOI':].apply(pd.to_numeric)
    
    # I ultimately want to remove this and fix it properly, but I need to build a model
    null_columns = df.columns[df.isnull().any()]
    df = df.drop(columns = null_columns)
    
    return df


def natstat_add_ave_stats(df_in, cols = None):
    ''' we want to create running averages for all of the numberic values of interest'''
    df = df_in.copy()
    
    # get cols to create averages of
    if cols is None:
        cols = df.loc[:, 'CF':].columns

    for c in cols:
        # create a column header name
        new_col = c + '_ave'
        
        # create the new column and fill with 0.0
        df[new_col] = 0.0
        
        # filter for each team and create the running average for each team individually
        for team in df.Team.sort_values().unique():
            df.loc[df['Team'] == team, new_col] = df.loc[df['Team'] == team, c].expanding(2).mean().shift(1)
            
    return df


def natstat_split_game_info(df_in):
    '''Split "Game" column into date, home team, away team, home goals, away goals'''
    df = df_in.copy()
    
    # get date and add it to the dataframe
    temp = df['Game'].str.split(' - ', n=1, expand = True)
    
    # temp[0] contains the date
    df.insert(0, 'date', pd.to_datetime(temp[0], format = '%Y-%m-%d'))
    
    # temp[1] contains the game information, but it is messy
    temp = temp[1].str.split(',', n=1, expand = True)
    
    # now temp[0] contains the away team information and temp[1] contains the home team information
    df.insert(1, 'home', temp[1].str.replace('\d+','').str.strip())
    df.insert(2, 'home_goals', temp[1].str.extract(r'(\d+)'))
    df.insert(3, 'away', temp[0].str.replace('\d+','').str.strip())
    df.insert(4, 'away_goals', temp[0].str.extract(r'(\d+)'))
    
    # in case we want to easily filter for home and away games we set H or A for each row
    hoa = ['H' if home_team in full_name else 'A' for home_team, full_name in zip(df['home'], df['Team'])]
    df.insert(5, 'hoa', hoa)
    
    # in case we want to easily filter for home and away games we set H or A for each row
    #['yes' if v == 1 else 'no' if v == 2 else 'idle' for v in l]
    #d = {1: 'yes', 2: 'no'}
    #results = {''}
    #winner = ['H_reg' if h and t <= 60.0
           #for h, a, t in zip(df['home_goals'], df['away_goals'], df['TOI'])]
    winner = []
    for h, a, t in zip(df['home_goals'], df['away_goals'], df['TOI']):
        result = ('H_reg' if h > a else 'A_reg' if t <= 60.0 else 
                  'H_OT' if h > a else 'A_OT' if t < 65.0 else
                  'H_SO' if h > a else 'A_SO')
        winner.append(result)
    df.insert(6, 'result', winner)
    
    
    return df


def natstat_home_away(df_in, hoa, col_suffix):
    '''
        Filter the original dataframe for home team or away team information that can be used to flatten each game
        
        Return two dataframes:
            header = data, home, away, home_goals, away_goals, hoa, Game, Team
            stats = all of the raw data
        
    '''
    df = df_in[df_in['hoa'] == hoa].copy()
    
    header = df.loc[:, 'date':'TOI'].reset_index(drop=True)
    stats = df.loc[:, 'CF':].reset_index(drop=True)

    header.columns = [col + '_' + col_suffix for col in header.columns]
    stats.columns = [col + '_' + col_suffix for col in stats.columns]
    
    return header, stats


def natstat_flatten(df_in):
    ''' combine all stats into a single row for each game  '''
    h_head, h_stats = natstat_home_away(df_in, 'H', 'home')
    a_head, a_stats = natstat_home_away(df_in, 'A', 'away')
    
    h_head.columns = np.char.replace(h_head.columns.values.astype(str), '_home', '')
    
    return pd.concat([h_head, h_stats, a_stats], axis = 1)


def natstat_build_df(df_in):
    df = natstat_to_numeric(df_in)
    df = natstat_add_ave_stats(df)
    df = natstat_split_game_info(df)
    df = natstat_flatten(df).reset_index(drop = True)
    
    return df

In [6]:
natstat2016 = pd.read_csv("Games - Natural Stat TrickTeam Season Totals - 2016.csv")
natstat2017 = pd.read_csv("Games - Natural Stat TrickTeam Season Totals - 2017.csv")
natstat2018 = pd.read_csv("Games - Natural Stat TrickTeam Season Totals - 2018.csv")

natstat2016_flat = natstat_build_df(natstat2016)
#natstat2017_flat = natstat_build_df(natstat2017)
#natstat2018_flat = natstat_build_df(natstat2018)

In [7]:
natstat2016_flat[natstat2016_flat.Team == 'Calgary Flames']

,date,home,home_goals,away,away_goals,hoa,result,Game,Team,TOI,...,LDSF_ave_away,LDSA_ave_away,LDSF%_ave_away,LDGF_ave_away,LDGA_ave_away,LDSH%_ave_away,LDSV%_ave_away,SH%_ave_away,SV%_ave_away,PDO_ave_away
15,2016-10-14,Flames,3,Oilers,5,H,A_reg,"2016-10-14 - Oilers 5, Flames 3",Calgary Flames,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2016-10-18,Flames,4,Sabres,3,H,H_reg,"2016-10-18 - Sabres 3, Flames 4",Calgary Flames,62.433333,...,12.000000,10.500000,51.850000,0.500000,0.000000,6.250000,100.000000,14.115000,88.635000,1.027500
56,2016-10-20,Flames,2,Hurricanes,4,H,A_reg,"2016-10-20 - Hurricanes 4, Flames 2",Calgary Flames,60.000000,...,15.666667,15.666667,48.636667,0.333333,1.333333,1.150000,93.400000,11.503333,85.720000,0.972000
66,2016-10-22,Flames,4,Blues,6,H,A_reg,"2016-10-22 - Blues 6, Flames 4",Calgary Flames,60.000000,...,10.600000,8.600000,52.148000,0.600000,0.000000,4.038000,100.000000,9.618000,90.702000,1.003400
111,2016-10-28,Flames,5,Senators,2,H,H_reg,"2016-10-28 - Senators 2, Flames 5",Calgary Flames,60.000000,...,13.666667,16.833333,46.428333,0.333333,1.000000,2.556667,94.081667,9.773333,89.018333,0.987667
122,2016-10-30,Flames,1,Capitals,3,H,A_reg,"2016-10-30 - Capitals 3, Flames 1",Calgary Flames,60.000000,...,14.000000,10.714286,55.295714,0.142857,0.142857,0.751429,98.571429,8.228571,92.067143,1.003143
203,2016-11-10,Flames,2,Stars,4,H,A_reg,"2016-11-10 - Stars 4, Flames 2",Calgary Flames,60.000000,...,14.384615,13.769231,51.072308,0.692308,0.769231,5.139231,93.295385,9.319231,87.816154,0.971462
217,2016-11-12,Flames,1,Rangers,4,H,A_reg,"2016-11-12 - Rangers 4, Flames 1",Calgary Flames,60.000000,...,10.642857,11.642857,47.912143,0.571429,0.214286,6.014286,97.962857,14.654286,90.530000,1.051643
242,2016-11-16,Flames,2,Coyotes,1,H,H_reg,"2016-11-16 - Coyotes 1, Flames 2",Calgary Flames,60.816667,...,14.500000,15.928571,47.907143,0.642857,0.857143,4.069286,94.920714,9.346429,89.572143,0.989214
254,2016-11-18,Flames,2,Blackhawks,3,H,A_reg,"2016-11-18 - Blackhawks 3, Flames 2",Calgary Flames,60.000000,...,13.352941,14.176471,48.154706,0.588235,0.529412,4.757647,95.990000,11.214706,91.685294,1.028941
341,2016-11-30,Flames,3,Maple Leafs,0,H,H_reg,"2016-11-30 - Maple Leafs 0, Flames 3",Calgary Flames,60.000000,...,12.727273,14.454545,44.381818,0.454545,0.545455,3.770000,96.111818,10.220455,90.276364,1.004955
357,2016-12-02,Flames,3,Wild,2,H,H_reg,"2016-12-02 - Wild 2, Flames 3",Calgary Flames,65.000000,...,15.272727,16.409091,47.185455,0.590909,0.409091,4.812727,97.570909,9.892727,93.162273,1.030591
371,2016-12-04,Flames,8,Ducks,3,H,H_reg,"2016-12-04 - Ducks 3, Flames 8",Calgary Flames,60.000000,...,12.920000,13.280000,49.735200,0.600000,0.480000,3.950800,95.574800,9.248800,91.593200,1.008360
414,2016-12-10,Flames,6,Jets,2,H,H_reg,"2016-12-10 - Jets 2, Flames 6",Calgary Flames,60.000000,...,12.400000,13.700000,46.627667,0.566667,0.566667,4.251667,95.490333,9.591000,89.776667,0.993567
442,2016-12-14,Flames,3,Lightning,6,H,A_reg,"2016-12-14 - Lightning 6, Flames 3",Calgary Flames,60.000000,...,14.310345,13.827586,50.777931,0.482759,0.689655,3.652069,94.327586,9.410000,90.667241,1.000828
452,2016-12-16,Flames,1,Blue Jackets,4,H,A_reg,"2016-12-16 - Blue Jackets 4, Flames 1",Calgary Flames,60.000000,...,12.074074,13.888889,46.153333,0.740741,0.444444,6.798889,96.650000,10.869630,92.949259,1.038259
506,2016-12-23,Flames,4,Canucks,1,H,H_reg,"2016-12-23 - Canucks 1, Flames 4",Calgary Flames,60.000000,...,12.588235,11.647059,52.626471,0.323529,0.500000,2.841765,96.355882,8.672353,89.593235,0.982647
536,2016-12-29,Flames,1,Ducks,3,H,A_reg,"2016-12-29 - Ducks 3, Flames 1",Calgary Flames,60.000000,...,12.500000,12.611111,50.304444,0.444444,0.583333,2.917222,94.643611,9.508056,89.914444,0.994222
550,2016-12-31,Flames,4,Coyotes,2,H,H_reg,"2016-12-31 - Coyotes 2, Flames 4",Calgary Flames,60.000000,...,13.527778,15.194444,47.490278,0.500000,0.666667,3.689722,95.700556,7.710278,90.145833,0.978528
570,2017-01-04,Flames,4,Avalanche,1,H,H_reg,"2017-01-04 - Avalanche 1, Flames 4",Calgary Flames,60.000000,...,14.297297,15.621622,47.909459,0.459459,0.513514,3.532162,96.502162,7.502432,89.155676,0.966541
591,2017-01-07,Flames,3,Canucks,1,H,H_reg,"2017-01-07 - Canucks 1, Flames 3",Calgary Flames,60.000000,...,11.317073,11.853659,48.747805,0.317073,0.487805,3.192927,96.248537,9.403902,90.448293,0.998488
621,2017-01-11,Flames,3,Sharks,2,H,H_reg,"2017-01-11 - Sharks 2, Flames 3",Calgary Flames,60.000000,...,13.170732,10.878049,54.611951,0.536585,0.487805,4.420244,95.488537,9.057805,91.400488,1.004659
633,2017-01-13,Flames,1,Devils,2,H,A_reg,"2017-01-13 - Devils 2, Flames 1",Calgary Flames,60.000000,...,12.813953,14.534884,47.305116,0.441860,0.534884,2.932791,96.685116,8.455116,90.499070,0.989558
665,2017-01-17,Flames,5,Panthers,2,H,H_reg,"2017-01-17 - Panthers 2, Flames 5",Calgary Flames,60.000000,...,15.822222,14.688889,51.730000,0.422222,0.711111,2.506444,95.456000,7.424222,91.477778,0.988956
679,2017-01-19,Flames,3,Predators,4,H,A_reg,"2017-01-19 - Predators 4, Flames 3",Calgary Flames,60.000000,...,13.795455,14.727273,48.093182,0.477273,0.522727,3.905455,96.377727,9.105455,91.225227,1.003341
697,2017-01-21,Flames,3,Oilers,7,H,A_reg,"2017-01-21 - Oilers 7, Flames 3",Calgary Flames,60.000000,...,12.791667,12.104167,50.895208,0.437500,0.479167,3.081250,96.196458,9.246042,90.928958,1.001833
755,2017-02-01,Flames,5,Wild,1,H,H_reg,"2017-02-01 - Wild 1, Flames 5",Calgary Flames,60.000000,...,13.591837,15.448980,45.798980,0.673469,0.387755,5.320204,97.611020,12.079388,92.702245,1.047898
832,2017-02-13,Flames,0,Coyotes,5,H,A_reg,"2017-02-13 - Coyotes 5, Flames 0",Calgary Flames,60.000000,...,13.169811,14.754717,47.827358,0.490566,0.566038,3.638491,96.311509,8.158491,90.109434,0.982623
842,2017-02-15,Flames,3,Flyers,1,H,H_reg,"2017-02-15 - Flyers 1, Flames 3",Calgary Flames,60.000000,...,15.303571,12.767857,55.224286,0.607143,0.464286,3.605536,95.792857,8.358036,89.124643,0.974857
925,2017-02-28,Flames,2,Kings,1,H,H_reg,"2017-02-28 - Kings 1, Flames 2",Calgary Flames,61.783333,...,14.612903,11.483871,56.078226,0.596774,0.370968,4.326935,97.021613,8.091129,90.236935,0.983323
949,2017-03-03,Flames,3,Red Wings,2,H,H_reg,"2017-03-03 - Red Wings 2, Flames 3",Calgary Flames,63.933333,...,12.000000,12.885246,48.718197,0.295082,0.491803,2.307705,96.418852,8.486721,89.895902,0.983820
964,2017-03-05,Flames,5,Islanders,2,H,H_reg,"2017-03-05 - Islanders 2, Flames 5",Calgary Flames,60.000000,...,11.761905,13.158730,46.847619,0.492063,0.634921,3.947937,95.020794,9.669365,90.853651,1.005159
983,2017-03-09,Flames,5,Canadiens,0,H,H_reg,"2017-03-09 - Canadiens 0, Flames 5",Calgary Flames,60.000000,...,14.149254,14.014925,50.282239,0.567164,0.656716,4.241493,95.499851,9.312090,91.516269,1.008284
1021,2017-03-13,Flames,4,Penguins,3,H,H_reg,"2017-03-13 - Penguins 3, Flames 4",Calgary Flames,65.000000,...,13.492537,13.940299,49.497164,0.462687,0.432836,3.597463,97.126119,10.350299,91.352985,1.017060
1031,2017-03-15,Flames,2,Bruins,5,H,A_reg,"2017-03-15 - Bruins 5, Flames 2",Calgary Flames,60.000000,...,15.101449,12.130435,55.621159,0.492754,0.362319,3.308116,97.315362,8.390580,90.006812,0.983957
1049,2017-03-17,Flames,3,Stars,1,H,H_reg,"2017-03-17 - Stars 1, Flames 3",Calgary Flames,60.000000,...,13.385714,13.114286,50.566714,0.414286,0.542857,2.847143,95.529286,9.712857,88.659000,0.983686
1063,2017-03-19,Flames,5,Kings,2,H,H_reg,"2017-03-19 - Kings 2, Flames 5",Calgary Flames,60.000000,...,14.771429,11.385714,56.538429,0.557143,0.371429,3.995857,96.990286,7.958571,90.364286,0.983286
1119,2017-03-27,Flames,4,Avalanche,2,H,H_reg,"2017-03-27 - Avalanche 2, Flames 4",Calgary Flames,60.000000,...,13.851351,15.391892,47.161622,0.445946,0.581081,3.523243,96.074054,7.316216,89.125676,0.964419
1139,2017-03-29,Flames,1,Kings,4,H,A_reg,"2017-03-29 - Kings 4, Flames 1",Calgary Flames,60.000000,...,14.800000,11.173333,57.038400,0.573333,0.360000,3.996133,96.924267,7.778267,90.224000,0.980080
1155,2017-03-31,Flames,5,Sharks,2,H,H_reg,"2017-03-31 - Sharks 2, Flames 5",Calgary Flames,60.000000,...,13.350649,11.324675,54.405455,0.467532,0.402597,3.616623,96.456883,9.086234,90.991948,1.000831
1168,2017-04-02,Flames,3,Ducks,4,H,A_reg,"2017-04-02 - Ducks 4, Flames 3",Calgary Flames,60.000000,...,12.230769,12.666667,48.831667,0.435897,0.397436,3.421410,96.402051,9.154744,91.456538,1.006128

### TO - DO
Deal with missing values - mostly in the percentage columns, but these are derived from other columns
I know that for some, like GF% the values are simply incorrectly recorded

skipping ahead for now - i want to build a model

In [8]:
#natstat2016_flat.loc[natstat2016_flat['GF%'].isnull(), ['GF', 'GA', 'GF%']]
#natstat2016_flat.loc[natstat2016_flat['GF%'].isnull(), :]
#natstat2016_flat.loc[natstat2016_flat.isnull(), :]
null_columns=natstat2016_flat.columns[natstat2016_flat.isnull().any()]

display(natstat2016_flat[natstat2016_flat.isnull().any(axis=1)][null_columns])
print(null_columns)

,CF_ave_home,CA_ave_home,CF%_ave_home,FF_ave_home,FA_ave_home,FF%_ave_home,SF_ave_home,SA_ave_home,SF%_ave_home,GF_ave_home,...,LDSF_ave_away,LDSA_ave_away,LDSF%_ave_away,LDGF_ave_away,LDGA_ave_away,LDSH%_ave_away,LDSV%_ave_away,SH%_ave_away,SV%_ave_away,PDO_ave_away
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,9.0,68.965,1.5,0.0,7.645,100.0,9.165,78.88,0.8805
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,47.000000,49.000000,48.695000,30.0,41.0,42.050000,21.500000,30.5,41.455,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,53.000000,46.000000,53.805000,43.0,30.0,59.235000,32.500000,20.0,61.885,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,50.000000,62.000000,44.635000,38.0,49.5,43.530000,28.500000,38.0,42.945,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,55.000000,64.000000,46.100000,42.5,50.0,45.450000,37.500000,38.5,48.905,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,57.666667,56.666667,51.466667,46.0,40.0,54.236667,33.333333,29.0,53.850,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Index(['CF_ave_home', 'CA_ave_home', 'CF%_ave_home', 'FF_ave_home',
       'FA_ave_home', 'FF%_ave_home', 'SF_ave_home', 'SA_ave_home',
       'SF%_ave_home', 'GF_ave_home', 'GA_ave_home', 'xGF_ave_home',
       'xGA_ave_home', 'SCF_ave_home', 'SCA_ave_home', 'SCF%_ave_home',
       'HDCF_ave_home', 'HDCA_ave_home', 'HDSF_ave_home', 'HDSA_ave_home',
       'HDGF_ave_home', 'HDGA_ave_home', 'MDCF_ave_home', 'MDCA_ave_home',
       'MDCF%_ave_home', 'MDSF_ave_home', 'MDSA_ave_home', 'MDSF%_ave_home',
       'MDGF_ave_home', 'MDGA_ave_home', 'LDCF_ave_home', 'LDCA_ave_home',
       'LDCF%_ave_home', 'LDSF_ave_home', 'LDSA_ave_home', 'LDSF%_ave_home',
       'LDGF_ave_home', 'LDGA_ave_home', 'LDSH%_ave_home', 'LDSV%_ave_home',
       'SH%_ave_home', 'SV%_ave_home', 'PDO_ave_home', 'CF_ave_away',
       'CA_ave_away', 'CF%_ave_away', 'FF_ave_away', 'FA_ave_away',
       'FF%_ave_away', 'SF_ave_away', 'SA_ave_away', 'SF%_ave_away',
       'GF_ave_away', 'GA_ave_away', 'xGF_ave_away', 'xGA_ave_away',
       'SCF_ave_away', 'SCA_ave_away', 'SCF%_ave_away', 'HDCF_ave_away',
       'HDCA_ave_away', 'HDSF_ave_away', 'HDSA_ave_away', 'HDGF_ave_away',
       'HDGA_ave_away', 'MDCF_ave_away', 'MDCA_ave_away', 'MDCF%_ave_away',
       'MDSF_ave_away', 'MDSA_ave_away', 'MDSF%_ave_away', 'MDGF_ave_away',
       'MDGA_ave_away', 'LDCF_ave_away', 'LDCA_ave_away', 'LDCF%_ave_away',
       'LDSF_ave_away', 'LDSA_ave_away', 'LDSF%_ave_away', 'LDGF_ave_away',
       'LDGA_ave_away', 'LDSH%_ave_away', 'LDSV%_ave_away', 'SH%_ave_away',
       'SV%_ave_away', 'PDO_ave_away'],
      dtype='object')

In [9]:
display(natstat2016_flat.head(6))

,date,home,home_goals,away,away_goals,hoa,result,Game,Team,TOI,...,LDSF_ave_away,LDSA_ave_away,LDSF%_ave_away,LDGF_ave_away,LDGA_ave_away,LDSH%_ave_away,LDSV%_ave_away,SH%_ave_away,SV%_ave_away,PDO_ave_away
0,2016-10-12,Blackhawks,2,Blues,5,H,A_reg,"2016-10-12 - Blues 5, Blackhawks 2",Chicago Blackhawks,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-10-12,Oilers,7,Flames,4,H,H_reg,"2016-10-12 - Flames 4, Oilers 7",Edmonton Oilers,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-10-12,Sharks,2,Kings,1,H,H_reg,"2016-10-12 - Kings 1, Sharks 2",San Jose Sharks,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-10-12,Senators,5,Maple Leafs,4,H,H_reg,"2016-10-12 - Maple Leafs 4, Senators 5",Ottawa Senators,60.616667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-10-13,Blue Jackets,3,Bruins,6,H,A_reg,"2016-10-13 - Bruins 6, Blue Jackets 3",Columbus Blue Jackets,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2016-10-13,Sabres,1,Canadiens,4,H,A_reg,"2016-10-13 - Canadiens 4, Sabres 1",Buffalo Sabres,60.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Find Marginal Stats for Each Game

So far we have:
* loaded the dataframes
* calculated the running average for each metric for each team
* converted each game into a flat structure

Now we can calculate the marginal stats for the difference between these stats.

In [10]:
h = np.core.defchararray.find(natstat2016_flat.columns.values.astype(str), 'ave_home') >= 0
a = np.core.defchararray.find(natstat2016_flat.columns.values.astype(str), 'ave_away') >= 0

homestats_2016 = natstat2016_flat.loc[:, h]
awaystats_2016 = natstat2016_flat.loc[:, a]

homestats_2016.columns = np.char.replace(homestats_2016.columns.values.astype(str), '_home', '')
awaystats_2016.columns = np.char.replace(homestats_2016.columns.values.astype(str), '_away', '')

marginal_stats_2016 = homestats_2016 - awaystats_2016
marginal_stats_2016

,CF_ave,CA_ave,CF%_ave,FF_ave,FA_ave,FF%_ave,SF_ave,SA_ave,SF%_ave,GF_ave,...,LDSF_ave,LDSA_ave,LDSF%_ave,LDGF_ave,LDGA_ave,LDSH%_ave,LDSV%_ave,SH%_ave,SV%_ave,PDO_ave
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,-5.456790,6.543210,-5.313333,-3.000000,5.666667,-5.384198,-1.654321,3.901235,-4.776420,0.246914,...,-2.432099,1.543210,-8.060247,-0.111111,0.037037,-0.406173,-0.516049,1.397531,1.294938,0.026901
1226,-0.148148,0.419753,-0.595432,-1.876543,-1.839506,-0.180741,-2.049383,-3.666667,1.283827,0.716049,...,-2.111111,-2.135802,0.529506,0.358025,-0.395062,3.286296,2.270617,3.203951,1.391728,0.045975
1227,-3.691358,-2.197531,-0.703457,-2.679012,-1.296296,-0.765062,-3.876543,-2.530864,-0.899383,-0.320988,...,-0.222222,-0.629630,1.307778,0.024691,0.074074,0.295309,-0.722469,0.392716,-0.481358,-0.001012
1228,2.222222,-6.395062,3.593210,0.975309,-5.098765,3.399753,-0.580247,-3.888889,2.513086,0.358025,...,-0.925926,-3.333333,3.874444,-0.012346,0.222222,0.484444,-2.907778,1.444568,-1.085926,0.003630
1229,0.123457,1.987654,-0.674815,0.518519,1.864198,-0.642346,0.358025,1.679012,-0.954444,0.382716,...,-2.604938,-0.975309,-3.534444,-0.234568,0.049383,-1.160370,-0.473580,1.026790,-0.441975,0.005901

### Should we try a very simple model?

I think so.

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
log = LogisticRegression(penalty='l1', solver='liblinear')

In [13]:
X_train = marginal_stats_2016.dropna().iloc[:-100]
X_test = marginal_stats_2016.dropna().iloc[-100:]

y_train = natstat2016_flat.iloc[X_train.index.values].result.apply(lambda x: 1 if x[0] == 'H' else 0)
y_test = natstat2016_flat.iloc[X_test.index.values].result.apply(lambda x: 1 if x[0] == 'H' else 0)

In [14]:
natstat2016_flat[natstat2016_flat['result'].isna()]

Empty DataFrame
Columns: [date, home, home_goals, away, away_goals, hoa, result, Game, Team, TOI, CF_home, CA_home, CF%_home, FF_home, FA_home, FF%_home, SF_home, SA_home, SF%_home, GF_home, GA_home, xGF_home, xGA_home, SCF_home, SCA_home, SCF%_home, HDCF_home, HDCA_home, HDSF_home, HDSA_home, HDGF_home, HDGA_home, MDCF_home, MDCA_home, MDCF%_home, MDSF_home, MDSA_home, MDSF%_home, MDGF_home, MDGA_home, LDCF_home, LDCA_home, LDCF%_home, LDSF_home, LDSA_home, LDSF%_home, LDGF_home, LDGA_home, LDSH%_home, LDSV%_home, SH%_home, SV%_home, PDO_home, CF_ave_home, CA_ave_home, CF%_ave_home, FF_ave_home, FA_ave_home, FF%_ave_home, SF_ave_home, SA_ave_home, SF%_ave_home, GF_ave_home, GA_ave_home, xGF_ave_home, xGA_ave_home, SCF_ave_home, SCA_ave_home, SCF%_ave_home, HDCF_ave_home, HDCA_ave_home, HDSF_ave_home, HDSA_ave_home, HDGF_ave_home, HDGA_ave_home, MDCF_ave_home, MDCA_ave_home, MDCF%_ave_home, MDSF_ave_home, MDSA_ave_home, MDSF%_ave_home, MDGF_ave_home, MDGA_ave_home, LDCF_ave_home, LDCA_ave_home, LDCF%_ave_home, LDSF_ave_home, LDSA_ave_home, LDSF%_ave_home, LDGF_ave_home, LDGA_ave_home, LDSH%_ave_home, LDSV%_ave_home, SH%_ave_home, SV%_ave_home, PDO_ave_home, CF_away, CA_away, CF%_away, FF_away, ...]
Index: []

[0 rows x 182 columns]

In [15]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(1097, 43) (1097,)
(100, 43) (100,)

In [16]:
log.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
log.score(X_train, y_train)

0.6071103008204193

In [18]:
log.score(X_test, y_test)

0.67

In [19]:
log.coef_

array([[ 0.        , -0.07096338,  0.        , -0.12938085,  0.02108885,
         0.        ,  0.09731925,  0.07647506,  0.        ,  0.        ,
         0.        ,  0.02662042,  0.19013263,  0.        ,  0.        ,
        -0.21082546,  0.33409212, -0.24714166,  0.        ,  0.01437741,
         0.        ,  0.        , -0.02108709,  0.21899701,  0.21518136,
        -0.16612123,  0.00343231,  0.05267563, -0.44530277,  0.        ,
         0.13324657,  0.02914943,  0.00794614, -0.1483903 ,  0.        ,
         0.03301258,  0.        ,  0.        ,  0.0709623 , -0.02566601,
         0.04702725,  0.0583532 ,  0.        ]])

In [20]:
temp = natstat2016_flat.iloc[X_test.index.values].copy()
temp['predict'] = log.predict(X_test)
display(temp[['date', 'home', 'away', 'home_goals', 'away_goals', 'result', 'predict']])

           date          home       away home_goals away_goals result  predict
1130 2017-03-28        Bruins  Predators          4          1  H_reg        1
1131 2017-03-28        Sharks    Rangers          5          4  H_reg        1
1132 2017-03-28    Hurricanes  Red Wings          4          1  H_reg        1
1133 2017-03-28  Blue Jackets     Sabres          3          1  H_reg        1
1134 2017-03-28        Flyers   Senators          3          2  H_reg        1
...         ...           ...        ...        ...        ...    ...      ...
1225 2017-04-09         Ducks      Kings          4          3  H_reg        1
1226 2017-04-09      Capitals   Panthers          0          2  A_reg        1
1227 2017-04-09       Rangers   Penguins          3          2  H_reg        0
1228 2017-04-09     Lightning     Sabres          4          2  H_reg        1
1229 2017-04-09     Islanders   Senators          4          2  H_reg        0

[100 rows x 7 columns]